# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xci
# IP: The module: 'starter_kit_demo_design_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xci
# IP: The module: 'starter_kit_demo_design_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
