# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/starter_kit_demo_design/starter_kit_demo_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design || ORIG_REF_NAME==starter_kit_demo_design}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_zynq_ultra_ps_e_0_0/starter_kit_demo_design_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==starter_kit_demo_design_zynq_ultra_ps_e_0_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_axi_gpio_0_1 || ORIG_REF_NAME==starter_kit_demo_design_axi_gpio_0_1}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_ps8_0_axi_periph_0_1/starter_kit_demo_design_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_ps8_0_axi_periph_0 || ORIG_REF_NAME==starter_kit_demo_design_ps8_0_axi_periph_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_rst_ps8_0_100M_0_1/starter_kit_demo_design_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_rst_ps8_0_100M_0 || ORIG_REF_NAME==starter_kit_demo_design_rst_ps8_0_100M_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_1_0_1/starter_kit_demo_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_axi_gpio_1_0 || ORIG_REF_NAME==starter_kit_demo_design_axi_gpio_1_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_xbar_0_1/starter_kit_demo_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_xbar_0 || ORIG_REF_NAME==starter_kit_demo_design_xbar_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_2_0_1/starter_kit_demo_design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_axi_gpio_2_0 || ORIG_REF_NAME==starter_kit_demo_design_axi_gpio_2_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_auto_ds_0 || ORIG_REF_NAME==starter_kit_demo_design_auto_ds_0}]

# IP: bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_pc_0/starter_kit_demo_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==starter_kit_demo_design_auto_pc_0 || ORIG_REF_NAME==starter_kit_demo_design_auto_pc_0}]

# XDC: bd/starter_kit_demo_design/starter_kit_demo_design_ooc.xdc
