# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xczu3eg-sfva625-1-i-es1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.cache/wt [current_project]
set_property parent.project_path C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultrazed_eg_iocc:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/hdl/starter_kit_demo_design_wrapper.v
add_files C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/starter_kit_demo_design.bd
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_zynq_ultra_ps_e_0_0/starter_kit_demo_design_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_zynq_ultra_ps_e_0_0/starter_kit_demo_design_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_0_1_1/starter_kit_demo_design_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_rst_ps8_0_100M_0_1/starter_kit_demo_design_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_rst_ps8_0_100M_0_1/starter_kit_demo_design_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_rst_ps8_0_100M_0_1/starter_kit_demo_design_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_1_0_1/starter_kit_demo_design_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_1_0_1/starter_kit_demo_design_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_1_0_1/starter_kit_demo_design_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_xbar_0_1/starter_kit_demo_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_2_0_1/starter_kit_demo_design_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_2_0_1/starter_kit_demo_design_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_axi_gpio_2_0_1/starter_kit_demo_design_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_pc_0/starter_kit_demo_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/starter_kit_demo_design_ooc.xdc]
set_property is_locked true [get_files C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/starter_kit_demo_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top starter_kit_demo_design_wrapper -part xczu3eg-sfva625-1-i-es1


write_checkpoint -force -noxdef starter_kit_demo_design_wrapper.dcp

catch { report_utilization -file starter_kit_demo_design_wrapper_utilization_synth.rpt -pb starter_kit_demo_design_wrapper_utilization_synth.pb }
