# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0.xci
# IP: The module: 'starter_kit_demo_design_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0.xci
# IP: The module: 'starter_kit_demo_design_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/tmcphill/GitRepos/ultrazed-eg-platforms/starter-kit-demo/starter-kit-demo.srcs/sources_1/bd/starter_kit_demo_design/ip/starter_kit_demo_design_auto_ds_0/starter_kit_demo_design_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'starter_kit_demo_design_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
